[build-system]
requires = ["scikit-build-core", "nanobind", "jax>0.5.0"]
build-backend = "scikit_build_core.build"

[project]
name = "cudakdtree_jax_binding"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["jax"]

[project.optional-dependencies]
test = ["pytest", "absl-py"]